### ISSUE TITLE
CoCreateInstance returns REGDB_E_CLASSNOTREG

### ISSUE THREAD

**Issue by rhard** [getbraincloud/braincloud-cpp#79]
Hi Team,

I'm trying to integrate SDK in my project using CMake. When trying to execute simple program I have a crash in XMLHTTPRequestLoader.cpp. The function CoCreateInstance cannot initialize pRequest. The output of the function is REGDB_E_CLASSNOTREG. I can't find an answer why CLSID_FreeThreadedXMLHTTP60 is not found.  The code starts at  Line 298:

```c++
CoCreateInstance(CLSID_FreeThreadedXMLHTTP60,
                             NULL,
                             CLSCTX_INPROC_SERVER,
                             IID_PPV_ARGS(&pRequest));
```

I 'v also tried to execute your gtest and got the same crash.
Windows 7, VS2015.

**Comment by davidstl** [comment]
Hi rhard,

That is very strange. I periodically run those tests locally, and we have a build server running them nightly. It could be your visual studio install is corrupted. Can you try repairing it? If repair doesn't work, maybe try uninstalling and reinstalling VS completely?

Another thought, are you trying to build in 64 bits of 32 bits? Just occurred to me we default our builds to 32 bits.

**Comment by rhard** [comment]
Hi David,

just tested with Win10 and VS2017. Everything is OK. However, if I move EXE to Windows 7 and run it, it still crashes. I think there are compatibility problems with older Windows versions. Maybe there is some build definition I need to set? Here is my CMakeLists.txt. I tried to add _WIN32_WINNT=0x600 but it doesn't help.
```cmake
cmake_minimum_required(VERSION 3.10)
project(BrainCloudTest)

set(CMAKE_CXX_STANDARD 11)

add_definitions(-D_WIN32_WINNT=0x600)

add_subdirectory(braincloud-cpp)

add_executable(BrainCloudTest main.cpp CloudWrapper.cpp CloudWrapper.h)
target_link_libraries(BrainCloudTest brainCloud)
```
P.S. I tried both x32 and x64 builds.

**Comment by davidstl** [comment]
Hum right I missed the point about windows 7.. that HTTP code might be windows 8+ only.
You might have to use Curl + OpenSSL for that.

The good news is, we have a build config for CURL because that's what we use on Linux. But the bad news that might be tricky to get working on windows because of openssl. You can modifying the cmake file to use CURL instead? You will need to install OpenSSL manually on windows and point to it. That's going to be the painful part.

**Comment by rhard** [comment]
I think I found why: https://docs.microsoft.com/en-us/windows/desktop/api/msxml6/nn-msxml6-ixmlhttprequest2

IXMLHTTPRequest2

![image](https://user-images.githubusercontent.com/8452952/56046809-61b63080-5d44-11e9-9296-d6ba141926b3.png)





`

**Comment by davidstl** [comment]
Ya... We're going to look into that.. Windows7 is still relevant for gamers. CURL will be the alternative here. You can try our CURL/OpenSSL setup for now and try to make that work. It will take a bit before we get to this. I'll log it now.

**Comment by rhard** [comment]
Thanks, I will try curl and let you know how it builds on Win.
BTW: Maybe you can add the check of CoCreateInstance return value with some error output. It will save some debugging time.

**Comment by davidstl** [comment]
Agreed, will update the JIRA

**Comment by davidstl** [comment]
Closing this, as it's been marked in our internal JIRA system and will be dealt with in time.

**Comment by rhard** [comment]
Could you advise me please how to enable CURL on windows? Do I need to disable USE_LIBWEBSOCKETS?
It already has SSL implementation but CURL uses OpenSSL. If I define USE_CURL 1 I have many SSL redefinitions from mbedtls.

**Comment by davidstl** [comment]
hum ya so you can use SSL instead of mbedtls if you go Curl. 
comment out that part in the cmake:
```
    # TLS
    option(ENABLE_TESTING "" OFF)
    option(ENABLE_PROGRAMS "" OFF)
    add_subdirectory(./lib/mbedtls/)
    list(APPEND libs PUBLIC mbedtls mbedx509 mbedcrypto)
    list(APPEND includes 
        PUBLIC ${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/include/)
    option(LWS_WITH_MBEDTLS "" ON)
    set(LWS_MBEDTLS_INCLUDE_DIRS
        "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/include/")
    if (UNIX AND NOT CMAKE_GENERATOR STREQUAL Xcode)
        set(LWS_MBEDTLS_LIBRARIES
            "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/libmbedtls.a"
            "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/libmbedcrypto.a"
            "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/libmbedx509.a")
    else()
        set(LWS_MBEDTLS_LIBRARIES 
            "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/")
    endif()
```

And LWS should pick up the OpenSSL you installed to have curl working.

**Comment by rhard** [comment]
Thanks! I got it working.

**Comment by davidstl** [comment]
Great news!
Do you mind sharing the cmake changes? I will put them in the ticket as a reference.

**Comment by rhard** [comment]
I updated libwebsockets reference to my own fork so I can't create pull request directly (there was some issues with OpenSSL Cmake entries). But I just added CURL check in the lines you mentioned above:
 
```cmake
if (NOT USE_CURL)
    # TLS
    option(ENABLE_TESTING "" OFF)
    option(ENABLE_PROGRAMS "" OFF)
    if (NOT USE_CURL)
        add_subdirectory(./lib/mbedtls/)
        list(APPEND libs PUBLIC mbedtls mbedx509 mbedcrypto)
        list(APPEND includes
            PUBLIC ${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/include/)
        option(LWS_WITH_MBEDTLS "" OFF)
        set(LWS_MBEDTLS_INCLUDE_DIRS
            "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/include/")
        if (UNIX AND NOT CMAKE_GENERATOR STREQUAL Xcode)
            set(LWS_MBEDTLS_LIBRARIES
                "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/libmbedtls.a"
                "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/libmbedcrypto.a"
                "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/libmbedx509.a")
        else()
            set(LWS_MBEDTLS_LIBRARIES
                "${CMAKE_CURRENT_BINARY_DIR}/lib/mbedtls/library/")
        endif()
    endif()
    # LibWebSockets
```

**Comment by rhard** [comment]
Update: the condition must be:
```cmake
if (NOT USE_CURL OR NOT WIN32)
```
otherwise it will not build on Linux.
